/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@interface PSSplitViewController : UISplitViewController {
    PSRootController *_containerNavigationController;
    id _navigationDelegate;
}

@property (nonatomic, retain) PSRootController *containerNavigationController;
@property (nonatomic) id navigationDelegate;

- (id)childViewControllerForStatusBarStyle;
- (void)popRecursivelyToRootController;
- (void)setupControllerForToolbar:(id)arg1;
- (void)showInitialViewController:(id)arg1;
- (unsigned int)supportedInterfaceOrientations;

@end
