/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

typedef enum PSTableCellType {
    PSGroupCell,
    PSLinkCell,
    PSLinkListCell,
    PSListItemCell,
    PSTitleValueCell,
    PSSliderCell,
    PSSwitchCell,
    PSStaticTextCell,
    PSEditTextCell,
    PSSegmentCell,
    PSGiantIconCell,
    PSGiantCell,
    PSSecureEditTextCell,
    PSButtonCell,
    PSEditTextViewCell
} PSSpecifierType;

@interface PSSpecifier : NSObject {
    SEL _buttonAction;
    SEL _confirmationAction;
    SEL _confirmationCancelAction;
    SEL _controllerLoadAction;
    NSString *_name;
    NSMutableDictionary *_properties;
    NSDictionary *_shortTitleDict;
    BOOL _showContentString;
    NSDictionary *_titleDict;
    id _userInfo;
    NSArray *_values;
    SEL action;
    int autoCapsType;
    int autoCorrectionType;
    SEL cancel;
    int cellType;
    Class detailControllerClass;
    Class editPaneClass;
    SEL getter;
    int keyboardType;
    SEL setter;
    id target;
    unsigned int textFieldType;
}

@property (nonatomic) SEL buttonAction;
@property (nonatomic) int cellType;
@property (nonatomic) SEL confirmationAction;
@property (nonatomic) SEL confirmationCancelAction;
@property (nonatomic) SEL controllerLoadAction;
@property (nonatomic) Class detailControllerClass;
@property (nonatomic) Class editPaneClass;
@property (nonatomic, retain) NSString *identifier;
@property (nonatomic, retain) NSString *name;
@property (nonatomic, retain) NSDictionary *shortTitleDictionary;
@property (nonatomic) BOOL showContentString;
@property (nonatomic) id target;
@property (nonatomic, retain) NSDictionary *titleDictionary;
@property (nonatomic, retain) id userInfo;
@property (nonatomic, retain) NSArray *values;

// Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences

+ (int)autoCapsTypeForString:(id)arg1;
+ (int)autoCorrectionTypeForNumber:(id)arg1;
+ (id)deleteButtonSpecifierWithName:(id)arg1 target:(id)arg2 action:(SEL)arg3;
+ (id)emptyGroupSpecifier;
+ (id)groupSpecifierWithID:(id)arg1;
+ (id)groupSpecifierWithID:(id)arg1 name:(id)arg2;
+ (id)groupSpecifierWithName:(id)arg1;
+ (int)keyboardTypeForString:(id)arg1;
+ (id)preferenceSpecifierNamed:(id)arg1 target:(id)arg2 set:(SEL)arg3 get:(SEL)arg4 detail:(Class)arg5 cell:(int)arg6 edit:(Class)arg7;
+ (id)specifierWithSpecifier:(id)arg1;

- (SEL)buttonAction;
- (int)cellType;
- (SEL)confirmationAction;
- (SEL)confirmationCancelAction;
- (SEL)controllerLoadAction;
- (id)description;
- (Class)detailControllerClass;
- (Class)editPaneClass;
- (BOOL)hasValidGetter;
- (BOOL)hasValidSetter;
- (id)identifier;
- (id)init;
- (BOOL)isEqualToSpecifier:(id)arg1;
- (SEL)legacyAction;
- (SEL)legacyCancel;
- (void)loadValuesAndTitlesFromDataSource;
- (id)name;
- (id)objectForKeyedSubscript:(id)arg1;
- (void)performButtonAction;
- (void)performConfirmationAction;
- (void)performConfirmationCancelAction;
- (void)performControllerLoadAction;
- (id)performGetter;
- (void)performLegacyAction;
- (void)performSetterWithValue:(id)arg1;
- (id)properties;
- (id)propertyForKey:(id)arg1;
- (void)removePropertyForKey:(id)arg1;
- (void)setButtonAction:(SEL)arg1;
- (void)setCellType:(int)arg1;
- (void)setConfirmationAction:(SEL)arg1;
- (void)setConfirmationCancelAction:(SEL)arg1;
- (void)setControllerLoadAction:(SEL)arg1;
- (void)setDetailControllerClass:(Class)arg1;
- (void)setEditPaneClass:(Class)arg1;
- (void)setIdentifier:(NSString*)arg1;
- (void)setKeyboardType:(int)arg1 autoCaps:(int)arg2 autoCorrection:(int)arg3;
- (void)setLegacyAction:(SEL)arg1;
- (void)setLegacyCancel:(SEL)arg1;
- (void)setName:(NSString*)arg1;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (void)setProperties:(id)arg1;
- (void)setProperty:(id)arg1 forKey:(id)arg2;
- (void)setShortTitleDictionary:(NSDictionary*)arg1;
- (void)setShowContentString:(BOOL)arg1;
- (void)setTarget:(id)arg1;
- (void)setTitleDictionary:(NSDictionary*)arg1;
- (void)setUserInfo:(id)arg1;
- (void)setValues:(NSArray*)arg1;
- (void)setValues:(id)arg1 titles:(id)arg2;
- (void)setValues:(id)arg1 titles:(id)arg2 shortTitles:(id)arg3;
- (void)setValues:(id)arg1 titles:(id)arg2 shortTitles:(id)arg3 usingLocalizedTitleSorting:(BOOL)arg4;
- (void)setupIconImageWithBundle:(id)arg1;
- (void)setupIconImageWithPath:(id)arg1;
- (BOOL)showContentString;
- (id)target;
- (int)titleCompare:(id)arg1;
- (id)userInfo;

@end
